# Generated by Django 5.2.6 on 2025-10-07 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QPaperGeneration', '0004_remove_qpattern_created_at_remove_subject_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('admin', 'Admin')], default='student', max_length=10),
        ),
    ]
