# Generated by Django 5.2.6 on 2025-10-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QPaperGeneration', '0006_studentgeneratedpaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgeneratedpaper',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
